name: Analyze Scraped Data

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["scrape"]
    types:
      - completed

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Set date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout scraper repo
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests jupyter nbconvert

      - name: List data directory contents for debug
        run: |
          echo "Current directory: $(pwd)"
          ls -l data

      - name: Execute analysis notebook
        run: |
          jupyter nbconvert --to notebook --execute analyze_jobs.ipynb --output output.ipynb --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.allow_errors=True

      - name: Debug output folder contents
        run: |
          echo "Contents of output:"
          ls -R output

      - name: Clone data-blog repository
        run: |
          git clone https://x-access-token:${{ secrets.BLOG_REPO_TOKEN }}@github.com/Flazoukie/data-blog.git data-blog

      - name: Copy analysis results to data-blog repo
        run: |
          mkdir -p data-blog/results/${{ steps.date.outputs.today }}
          cp -r output/${{ steps.date.outputs.today }}/* data-blog/results/${{ steps.date.outputs.today }}/

      - name: Commit and push results to data-blog
        run: |
          cd data-blog
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add results/*
          git commit -m "Add latest analysis results ${{ steps.date.outputs.today }}" || echo "No changes to commit"
          git push

