name: Analyze Scraped Data

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests jupyter nbconvert

      - name: List data directory contents for debug
        run: |
          echo "Current directory: $(pwd)"
          ls -l data

      - name: Execute analysis notebook
        run: |
          jupyter nbconvert --to notebook --execute analyze_jobs.ipynb --output output.ipynb --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.allow_errors=True

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: analysis-output
          path: output

      - name: Trigger publish workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          token: ${{ secrets.BLOG_REPO_TOKEN }}

