name: Publish Weekly Job Post

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no commit/push)?'
        required: false
        default: 'false'

  workflow_run:
    workflows: ["Analyze Scraped Data"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - id: date
        run: |
          echo "iso=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "german=$(date +'%d/%m/%Y')" >> $GITHUB_OUTPUT

      - name: Checkout blog repository
        uses: actions/checkout@v3
        with:
          repository: Flazoukie/data-blog
          token: ${{ secrets.BLOG_REPO_TOKEN }}
          path: data-blog

      - name: Generate new weekly post
        working-directory: data-blog
        run: |
          DATE=${{ steps.date.outputs.iso }}
          DISPLAY_DATE=${{ steps.date.outputs.german }}
          POST_FILENAME="posts/${DATE}-weekly-results.qmd"
          RESULTS_DIR="results/${DATE}"

          mkdir -p posts

          cat <<EOF > $POST_FILENAME
---
title: "Weekly Job Market Analysis - $DISPLAY_DATE"
date: $DATE
author: Flavia Felletti
image: /images/weekly_job_analysis.jpg
---

Welcome to the weekly update of the data science job market in Germany!

This analysis is based on the latest job postings collected via the [Adzuna API](https://developer.adzuna.com/), a comprehensive job search API that aggregates job offers from multiple sources.

All the data fetching, cleaning, and analysis code is publicly available on GitHub in my [\`adzuna-scraper-cleaned\`](https://github.com/Flazoukie/adzuna-scraper-cleaned) repository. This project runs automatically every week to provide fresh insights.

If you are interested in more details, you can check this [post](https://flazoukie.github.io/data-blog/posts/analyze_jobs.html) where I published the whole first analysis with detailed explanations.

## What you'll find in this post
- A bar plot highlighting the **top cities** with the most data science job offers.
- An **interactive company map** showing where employers are located.
- An **interactive job table** that allows you to explore individual job postings.

## Publishing cadence
I publish this job market analysis on my blog every **Monday**, so you can stay up to date with the latest trends and opportunities.

## Visualizations
### Top Cities for Job Offers
![](/$RESULTS_DIR/top_cities.png){ width=70% }

### Interactive Company Map
<iframe src="/$RESULTS_DIR/company_map.html" width="100%" height="600px"></iframe>

### Interactive Job Table
<iframe src="/$RESULTS_DIR/interactive_job_table.html" width="100%" height="600px"></iframe>

You can also [download the full analysis notebook here](/$RESULTS_DIR/output.ipynb) to explore the details yourself.

---

Thank you for reading! If you want to contribute or ask questions, feel free to reach out.
EOF

      - name: Show created post
        working-directory: data-blog
        run: |
          echo "Post created:"
          ls -lh posts

      - name: Commit and push new post
        if: ${{ github.event.inputs.dry_run != 'true' }}
        working-directory: data-blog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add posts
          git commit -m "Add weekly job post for ${{ steps.date.outputs.iso }}" || echo "No changes to commit"
          git push

