name: Publish Analysis to Blog

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: pip install pandas matplotlib folium

      - name: Run publishing script
        run: python publish_to_blog.py

      - name: Commit & push to blog
        working-directory: blog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Adzuna analysis results for $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.BLOG_TOKEN }}@github.com/Flazoukie/data-blog.git HEAD:main
